///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConcentricityBasler1inch
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the ConcentricityBasler1inchRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("e0391aac-e4cb-4975-962a-6321014a0cc5")]
    public partial class ConcentricityBasler1inchRepository : RepoGenBaseFolder
    {
        static ConcentricityBasler1inchRepository instance = new ConcentricityBasler1inchRepository();
        ConcentricityBasler1inchRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        ConcentricityBasler1inchRepositoryFolders.OpenSnapXRoutineAppFolder _opensnapxroutine;
        ConcentricityBasler1inchRepositoryFolders.ConcentricitySTANotepadAppFolder _concentricitystanotepad;
        ConcentricityBasler1inchRepositoryFolders.SizeacrossSTANotepadAppFolder _sizeacrossstanotepad;

        /// <summary>
        /// Gets the singleton class instance representing the ConcentricityBasler1inchRepository element repository.
        /// </summary>
        [RepositoryFolder("e0391aac-e4cb-4975-962a-6321014a0cc5")]
        public static ConcentricityBasler1inchRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ConcentricityBasler1inchRepository() 
            : base("ConcentricityBasler1inchRepository", "/", null, 0, false, "e0391aac-e4cb-4975-962a-6321014a0cc5", ".\\RepositoryImages\\ConcentricityBasler1inchRepositorye0391aac.rximgres")
        {
            _snapxuntitled = new ConcentricityBasler1inchRepositoryFolders.SnapXUntitledAppFolder(this);
            _opensnapxroutine = new ConcentricityBasler1inchRepositoryFolders.OpenSnapXRoutineAppFolder(this);
            _concentricitystanotepad = new ConcentricityBasler1inchRepositoryFolders.ConcentricitySTANotepadAppFolder(this);
            _sizeacrossstanotepad = new ConcentricityBasler1inchRepositoryFolders.SizeacrossSTANotepadAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e0391aac-e4cb-4975-962a-6321014a0cc5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("50c1a377-372e-4c5f-85fd-35cfbc5ba70a")]
        public virtual ConcentricityBasler1inchRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The OpenSnapXRoutine folder.
        /// </summary>
        [RepositoryFolder("89a9ca5f-1d07-4dff-94d7-8ed936760baa")]
        public virtual ConcentricityBasler1inchRepositoryFolders.OpenSnapXRoutineAppFolder OpenSnapXRoutine
        {
            get { return _opensnapxroutine; }
        }

        /// <summary>
        /// The ConcentricitySTANotepad folder.
        /// </summary>
        [RepositoryFolder("6803dd8e-3221-4711-99a8-a6a46b5a52bf")]
        public virtual ConcentricityBasler1inchRepositoryFolders.ConcentricitySTANotepadAppFolder ConcentricitySTANotepad
        {
            get { return _concentricitystanotepad; }
        }

        /// <summary>
        /// The SizeacrossSTANotepad folder.
        /// </summary>
        [RepositoryFolder("6fdef5cf-7501-41af-9ccc-ab91d2b4c38f")]
        public virtual ConcentricityBasler1inchRepositoryFolders.SizeacrossSTANotepadAppFolder SizeacrossSTANotepad
        {
            get { return _sizeacrossstanotepad; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class ConcentricityBasler1inchRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("50c1a377-372e-4c5f-85fd-35cfbc5ba70a")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _snapxuntitledInfo;
            RepoItemInfo _runroutinebuttonokInfo;
            RepoItemInfo _finishInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 100000, null, true, "50c1a377-372e-4c5f-85fd-35cfbc5ba70a", "")
            {
                _snapxuntitledInfo = new RepoItemInfo(this, "SnapXUntitled", "titlebar[@accessiblerole='TitleBar']", 100000, null, "3dfb02bf-9626-457a-abb5-176a4d709bc2");
                _runroutinebuttonokInfo = new RepoItemInfo(this, "RunRoutineButtonOK", "container/form/?/?/element[@controlid='59649']/?/button[@text='&OK' and @enabled='True']", 100000, null, "8277664b-deae-493f-9770-695a0dd7c4da");
                _finishInfo = new RepoItemInfo(this, "Finish", "container/form/?/?/element/element[@controlid='59648']/container/button[@text='Finish' and @enabled='True']", 100000, null, "c01b7d51-80f5-47da-9c00-845f390fc56d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("50c1a377-372e-4c5f-85fd-35cfbc5ba70a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("50c1a377-372e-4c5f-85fd-35cfbc5ba70a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SnapXUntitled item.
            /// </summary>
            [RepositoryItem("3dfb02bf-9626-457a-abb5-176a4d709bc2")]
            public virtual Ranorex.TitleBar SnapXUntitled
            {
                get
                {
                    return _snapxuntitledInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The SnapXUntitled item info.
            /// </summary>
            [RepositoryItemInfo("3dfb02bf-9626-457a-abb5-176a4d709bc2")]
            public virtual RepoItemInfo SnapXUntitledInfo
            {
                get
                {
                    return _snapxuntitledInfo;
                }
            }

            /// <summary>
            /// The RunRoutineButtonOK item.
            /// </summary>
            [RepositoryItem("8277664b-deae-493f-9770-695a0dd7c4da")]
            public virtual Ranorex.Button RunRoutineButtonOK
            {
                get
                {
                    return _runroutinebuttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RunRoutineButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("8277664b-deae-493f-9770-695a0dd7c4da")]
            public virtual RepoItemInfo RunRoutineButtonOKInfo
            {
                get
                {
                    return _runroutinebuttonokInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("c01b7d51-80f5-47da-9c00-845f390fc56d")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("c01b7d51-80f5-47da-9c00-845f390fc56d")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }
        }

        /// <summary>
        /// The OpenSnapXRoutineAppFolder folder.
        /// </summary>
        [RepositoryFolder("89a9ca5f-1d07-4dff-94d7-8ed936760baa")]
        public partial class OpenSnapXRoutineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text1148Info;

            /// <summary>
            /// Creates a new OpenSnapXRoutine  folder.
            /// </summary>
            public OpenSnapXRoutineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenSnapXRoutine", "/form[@title='Open Snap-X Routine']", parentFolder, 30000, null, true, "89a9ca5f-1d07-4dff-94d7-8ed936760baa", "")
            {
                _text1148Info = new RepoItemInfo(this, "Text1148", "?/?/text[@controlid='1148']", 30000, null, "c8388c59-3bd9-43d6-9022-bef3be0fe68b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("89a9ca5f-1d07-4dff-94d7-8ed936760baa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("89a9ca5f-1d07-4dff-94d7-8ed936760baa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text1148 item.
            /// </summary>
            [RepositoryItem("c8388c59-3bd9-43d6-9022-bef3be0fe68b")]
            public virtual Ranorex.Text Text1148
            {
                get
                {
                    return _text1148Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1148 item info.
            /// </summary>
            [RepositoryItemInfo("c8388c59-3bd9-43d6-9022-bef3be0fe68b")]
            public virtual RepoItemInfo Text1148Info
            {
                get
                {
                    return _text1148Info;
                }
            }
        }

        /// <summary>
        /// The ConcentricitySTANotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("6803dd8e-3221-4711-99a8-a6a46b5a52bf")]
        public partial class ConcentricitySTANotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ConcentricitySTANotepad  folder.
            /// </summary>
            public ConcentricitySTANotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ConcentricitySTANotepad", "/form[@title~'^concentricity\\.STA\\ -\\ Notep']", parentFolder, 30000, null, true, "6803dd8e-3221-4711-99a8-a6a46b5a52bf", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "f7e8d5ca-735b-478d-bd4c-ccd77811cd9a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6803dd8e-3221-4711-99a8-a6a46b5a52bf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6803dd8e-3221-4711-99a8-a6a46b5a52bf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("f7e8d5ca-735b-478d-bd4c-ccd77811cd9a")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("f7e8d5ca-735b-478d-bd4c-ccd77811cd9a")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The SizeacrossSTANotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("6fdef5cf-7501-41af-9ccc-ab91d2b4c38f")]
        public partial class SizeacrossSTANotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new SizeacrossSTANotepad  folder.
            /// </summary>
            public SizeacrossSTANotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SizeacrossSTANotepad", "/form[@title='sizeacross.STA - Notepad']", parentFolder, 30000, null, true, "6fdef5cf-7501-41af-9ccc-ab91d2b4c38f", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "928041bf-50f9-490e-9cf2-b7c7342c059a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6fdef5cf-7501-41af-9ccc-ab91d2b4c38f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6fdef5cf-7501-41af-9ccc-ab91d2b4c38f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("928041bf-50f9-490e-9cf2-b7c7342c059a")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("928041bf-50f9-490e-9cf2-b7c7342c059a")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

    }
#pragma warning restore 0436
}